=== vertigo-io/vertigo-lts-libs/vertigo-account-plugin-authorization-basic/src/main/java/io/vertigo/account/plugins/authorization/xml/loader/vertigo-security_1_0.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="authorisationConfig">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="permission" type="permission" />
				<xs:element name="role" type="role" />
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="permission">
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="operation" type="xs:string" use="required"/>
		<xs:attribute name="filter" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="role">	
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="permission" type="permissionRef" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"/>
		<xs:attribute name="description" type="xs:string" use="required"/>		
	</xs:complexType>
	
	<xs:complexType name="permissionRef">
		<xs:attribute name="ref" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== vertigo-io/vertigo-lts-libs/vertigo-account-plugin-authorization-basic/src/test/java/io/vertigo/account/authorization/basic/basic-auth-config.xml
<?xml version="1.0" encoding="UTF-8"?>

<authorisationConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="vertigo-security_1_0.xsd">
       
  	<!--  Permissions -->	
	<permission id="PRM_READ_ALL_PRODUCTS" operation="READ" filter="/products/.*" description="Lire tous les produits"/>		
	<permission id="PRM_WRITE_ALL_PRODUCTS" operation="WRITE" filter="/products/.*"  description="CrÃ©er/Modifier un produit"/>				
	
	<permission id="PRM_READ_ALL_FAMILLES" operation="READ" filter="/famille/.*" description="Lire toutes les familles"/>		
	<permission id="PRM_READ_MY_FAMILLE" operation="READ" filter="/famille/${famId}" description="Lire ma famille"/>		
	
	<!-- Roles -->
	<role name="R_READER" description="Lecteur de l'application">	  	   
  		<permission ref="PRM_READ_ALL_PRODUCTS"/>	
  	</role>

  	<role name="R_WRITER" description="Ecrivain de l'application">	  	   
  		<permission ref="PRM_READ_ALL_PRODUCTS" />
  		<permission ref="PRM_WRITE_ALL_PRODUCTS" />
  	</role>
  	
  	<role name="R_ALL_FAMILLES" description="Administeur de l'application">
  		<permission ref="PRM_READ_ALL_FAMILLES" />		
  	</role>

  	<role name="R_MY_FAMILLE" description="Lecteur de l'application">	  	   
  		<!--permission type="read" filter="/product/*"  -->
  		<permission ref="PRM_READ_MY_FAMILLE"/>
  	</role>
</authorisationConfig>
